server:
  port: 9998

spring:
  application:
    name: gateway

app:
  jwtSecret: labplatformSecretKey123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

logging:
  level:
    org.springframework.web.cors: DEBUG
    com.example.gateway: DEBUG
    com.example.gateway.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
