server:
  port: 9998

spring:
  application:
    name: gateway

app:
  jwtSecret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.cors: DEBUG
    com.example.gateway: DEBUG
